"""initial schema

Revision ID: 1e3eb60714a3
Revises: 
Create Date: 2026-02-15 09:34:59.736403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e3eb60714a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_ohlcv_symbol_tf_ts')
    )
    op.create_index(op.f('ix_ohlcv_symbol'), 'ohlcv', ['symbol'], unique=False)
    op.create_index(op.f('ix_ohlcv_timestamp'), 'ohlcv', ['timestamp'], unique=False)
    op.create_table('sentiment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_data_symbol'), 'sentiment_data', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='signaldirection'), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_1', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_3', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'EXPIRED', 'HIT_TP', 'HIT_SL', 'CANCELLED', name='signalstatus'), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('quote', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_order_size', sa.Float(), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('qty_precision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=True)
    op.create_table('whale_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('from_type', sa.String(length=20), nullable=False),
    sa.Column('to_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_whale_transactions_symbol'), 'whale_transactions', ['symbol'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='signaldirection'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('size_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_whale_transactions_symbol'), table_name='whale_transactions')
    op.drop_table('whale_transactions')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sentiment_data_symbol'), table_name='sentiment_data')
    op.drop_table('sentiment_data')
    op.drop_index(op.f('ix_ohlcv_timestamp'), table_name='ohlcv')
    op.drop_index(op.f('ix_ohlcv_symbol'), table_name='ohlcv')
    op.drop_table('ohlcv')
    # ### end Alembic commands ###
